### PR TITLE
UI overhaul and per-resource error reporting

### LINKED ISSUE #357: Improve legibility with table report
It can be difficult to understand what actually happened in a given cloud-nuke run because: 
1. We log everything to `stdout` which quickly becomes difficult to scan for non-trivial jobs
2. cloud-nuke occasionally returns `nil` for an error state even if the resource failed to be deleted successfully. We should try to clean these cases up by ensuring that an error returned during deletion is reflected in the final table

### PR DESCRIPTION
**Pull request by zackproser**
## Demo

* [Nuking multiple resource types, mix of success and error outcomes](https://asciinema.org/a/CniiLV21a4QaOQo5tO2ZaLW9o)
* [Nuking multiple resource types successfully](https://asciinema.org/a/CpLvZOXGm2PeTHoty0vg17l02)
## Description

These changes: 
* Implement support for displaying the status of a given cloud-nuke run in a pterm.sh table 
* Attempt to provide a per-resource status that is more accurate, rather than returning `nil` when something in a batch process fails
* Suppress excessive `stdout` logging by replacing all `Infof` calls with `Debugf`, so that the original information can still be retrieved by passing `--log-level DEBUG`
* Implement a spinner that displays `Nuking resources...` for the duration of the cloud-nuke run. On run completion, the spinner is replaced with the table. 

These changes are conceived of as an incremental improvement to the legibility of cloud-nuke's output, and a prerequisite to work that will leverage cloud-nuke to programmatically tear down deployed Reference Architectures.

### Example tables

```
❯ aws-vault exec nuketest -- ./cloud-nuke \
  aws \
  --region us-east-1 \
  --resource-type sqs \
  --resource-type snstopic \
  --resource-type lambda \
  --resource-type elasticache
[cloud-nuke] INFO[2022-09-06T14:50:16-04:00] The following resource types will be nuked:
[cloud-nuke] INFO[2022-09-06T14:50:16-04:00] - sqs
[cloud-nuke] INFO[2022-09-06T14:50:16-04:00] - snstopic
[cloud-nuke] INFO[2022-09-06T14:50:16-04:00] - lambda
[cloud-nuke] INFO[2022-09-06T14:50:16-04:00] - elasticache
[cloud-nuke] INFO[2022-09-06T14:50:17-04:00] Retrieving active AWS resources in [us-east-1]
[cloud-nuke] INFO[2022-09-06T14:50:18-04:00] The following 2 AWS resources will be nuked:
[cloud-nuke] INFO[2022-09-06T14:50:18-04:00] * lambda myFunction us-east-1
[cloud-nuke] INFO[2022-09-06T14:50:18-04:00] * elasticache test-redis us-east-1

THE NEXT STEPS ARE DESTRUCTIVE AND COMPLETELY IRREVERSIBLE, PROCEED WITH CAUTION!!!

Are you sure you want to nuke all listed resources? Enter 'nuke' to confirm (or exit with ^C): nuke

Nuking complete:

┌─────────────────────────────────────────────────────┐
| Identifier | Resource Type   | Deleted Successfully |
| myFunction | Lambda function |      ✅              |
| --------------------------------------------------- |
| test-redis | Elasticache     |      ✅              |
└─────────────────────────────────────────────────────┘
```

```

❯ aws-vault exec nuketest -- ./cloud-nuke \
  aws \
  --region us-east-1 \
  --resource-type sqs \
  --resource-type snstopic \
  --resource-type lambda \
  --resource-type elasticache
[cloud-nuke] INFO[2022-09-06T15:03:02-04:00] The following resource types will be nuked:
[cloud-nuke] INFO[2022-09-06T15:03:02-04:00] - sqs
[cloud-nuke] INFO[2022-09-06T15:03:02-04:00] - snstopic
[cloud-nuke] INFO[2022-09-06T15:03:02-04:00] - lambda
[cloud-nuke] INFO[2022-09-06T15:03:02-04:00] - elasticache
[cloud-nuke] INFO[2022-09-06T15:03:03-04:00] Retrieving active AWS resources in [us-east-1]
[cloud-nuke] INFO[2022-09-06T15:03:04-04:00] The following 3 AWS resources will be nuked:
[cloud-nuke] INFO[2022-09-06T15:03:04-04:00] * snstopic arn:aws:sns:us-east-1:297077893752:TopicOne us-east-1
[cloud-nuke] INFO[2022-09-06T15:03:04-04:00] * snstopic arn:aws:sns:us-east-1:297077893752:TopicThree us-east-1
[cloud-nuke] INFO[2022-09-06T15:03:04-04:00] * snstopic arn:aws:sns:us-east-1:297077893752:TopicTwo.fifo us-east-1

THE NEXT STEPS ARE DESTRUCTIVE AND COMPLETELY IRREVERSIBLE, PROCEED WITH CAUTION!!!

Are you sure you want to nuke all listed resources? Enter 'nuke' to confirm (or exit with ^C): nuke

Nuking complete:

┌─────────────────────────────────────────────────────────────────────────────────────────┐
| Identifier                                       | Resource Type | Deleted Successfully |
| arn:aws:sns:us-east-1:297077893752:TopicThree    | SNS Topic     |      ✅              |
| --------------------------------------------------------------------------------------- |
| arn:aws:sns:us-east-1:297077893752:TopicOne      | SNS Topic     |      ✅              |
| --------------------------------------------------------------------------------------- |
| arn:aws:sns:us-east-1:297077893752:TopicTwo.fifo | SNS Topic     |      ✅              |
└─────────────────────────────────────────────────────────────────────────────────────────┘
```

Fixes #357.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: report/record.go [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import (
+	"io"
+	"sync"
+
+	"github.com/pterm/pterm"
+)
+
+var m = &sync.Mutex{}
+
+var records = make(map[string]Entry)
```
Comment (hongil0316) [inline report/record.go:12]: Hey @zackproser, have we considered `NukeAllResources` method returning the status of each `nuke` operation, rather than using global + mutex pattern? 

I can think of one benefit as having full understanding of what the `NukeAllResources` method does without worrying about side outputs it produce via global variables.

**Comment by hongil0316** [comment]
Overall, LGTM 👍

File: report/record.go [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+	for idx := range data {
+		tableData = append(tableData, data[idx])
+	}
+	pterm.DefaultTable.
+		WithHasHeader().
+		WithBoxed(true).
+		WithRowSeparator("-").
+		WithData(tableData).
+		WithWriter(w).
+		Render()
```
Comment (denis256) [inline report/record.go:73]: Unchecked returned error from `Render()` function

Comment (zackproser) [reply report/record.go:73]: Ah, thank you good catch.

Comment (zackproser) [reply report/record.go:74]: Fixed in [304ac6c](https://github.com/gruntwork-io/cloud-nuke/pull/356/commits/304ac6c19eb2531fa9d77ba9753756241cbc314a)

File: report/record.go (hunk 1 above)
Comment (zackproser) [reply report/record.go:13]: Ah interesting. I hadn't considered that but you could well be right about the approach. Could you please elaborate a bit more on how that would work to ensure I understand?

Is your chief concern the use of the `m` and `records` variables within this package? They should only be usable by methods within this package to prevent race conditions.

**Review by denis256 — DISMISSED** [review]

File: spinner/spinner.go [hunk 3]
```diff
@@ -0,0 +1,15 @@
+package spinner
```
Comment (zackproser) [inline spinner/spinner.go:1]: Drop in favor of in-lining simple spinners where they're needed and cleaning them up immediately.

File: commands/cli.go [hunk 4]
```diff
@@ -241,6 +264,10 @@ func awsNuke(c *cli.Context) error {
 			return err
 		}
 		if proceed {
+
+			fmt.Println()
```
Comment (zackproser) [inline commands/cli.go:268]: Strike

File: commands/cli.go [hunk 5]
```diff
@@ -180,12 +183,20 @@ func awsNuke(c *cli.Context) error {
...
+	targetedResourceList := []pterm.BulletListItem{}
+
+	for _, resource := range resourceTypes {
+		targetedResourceList = append(targetedResourceList, pterm.BulletListItem{Level: 0, Text: resource})
 	}
 
+	ui.WarningMessage("The following resource types are targeted for destruction")
+
+	// Log which resource types will be nuked
+	pterm.DefaultBulletList.
```
Comment (zackproser) [inline commands/cli.go:195]: Handle error returned by `Render`.

File: commands/cli.go [hunk 6]
```diff
@@ -209,26 +220,40 @@ func awsNuke(c *cli.Context) error {
 		return errors.WithStackTrace(err)
 	}
 
-	logging.Logger.Infof("Retrieving active AWS resources in [%s]", strings.Join(targetRegions[:], ", "))
+	spinnerMsg := fmt.Sprintf("Retrieving active AWS resources in [%s]", strings.Join(targetRegions[:], ", "))
+
+	// Start a simple spinner to track progress reading all relevant AWS resources
+	spinnerSuccess, _ := pterm.DefaultSpinner.
```
Comment (zackproser) [inline commands/cli.go:226]: Handle error

File: commands/cli.go [hunk 7]
```diff
@@ -209,26 +220,40 @@ func awsNuke(c *cli.Context) error {
...
+	ui.WarningMessage(fmt.Sprintf("The following %d AWS resources will be nuked:\n", len(nukableResources)))
+
+	items := []pterm.BulletListItem{}
 
 	for _, resource := range nukableResources {
-		logging.Logger.Infoln(resource)
+		items = append(items, pterm.BulletListItem{Level: 0, Text: resource})
 	}
 
+	pterm.DefaultBulletList.
```
Comment (zackproser) [inline commands/cli.go:252]: Handle error returned by `Render`.

**Comment by zackproser** [comment]
(Note to anyone who is following along. I'll plan to pick this up again when I return to the office. If anyone on the team wants to merge this in the meantime, that's fine, too!)

**Review by pete0emerson — APPROVED** [review]
@pete0emerson and @ellisonc reviewed this live to understand it as best we can, and we're going to move it forward and commit it.
