### PR TITLE
Fix Config file not including when there is a 'exclude' rule

### LINKED ISSUE #198: Config file with only exclude rules do not work as expected
I don't remember if this was intentional or not.

If you create a config file where there is only an exclude rule, intuitively this should mean "include everything but what is requested to be excluded," but in practice this becomes "exclude everything" because `cloud-nuke` treats empty `include` rules as "include nothing."

You can work around this by adding an explicit `include` rule to include everything:

```yaml
s3:
  include:
    names_regex:
      - ".*"
  exclude:
    names_regex:
      - "^my-real-s3-bucket$"
```

### PR DESCRIPTION
**Pull request by marinalimeira**
Fixes #198.

Refactored the function `ShouldInclude` to behave properly when there is a `exclude` but no `include` config. I added a unit test to this function that catches the bug in question.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -79,27 +79,22 @@ func matches(name string, regexps []Expression) bool {
...
-		}
-	} else if len(excludeREs) > 0 {
-		// Only check to see if an exclude rule matches when there are no include rules defined
-		if matches(name, excludeREs) {
-			shouldInclude = false
-		}
+	// If no rules are defined, should always include
+	if len(includeREs) == 0 && len(excludeREs) == 0 {
+		return true
+		// If a rule that exclude matches, should not include
```
Comment (brikis98) [inline config/config.go:87]: NIT: indentation on this comment and the ones below seems off...

File: config/config.go [hunk 2]
```diff
@@ -79,27 +79,22 @@ func matches(name string, regexps []Expression) bool {
...
+		// Given the 'name' is not in the 'exclude' list, should include if there is no 'include' list
+	} else if len(includeREs) == 0 {
+		return true
+		// Given there is a 'include' list, and 'name' is there, should include
+	} else if matches(name, includeREs) {
+		return true
+		// If it's not in the 'include' list, should not include
 	} else {
-		shouldInclude = true
+		return false
```
Comment (brikis98) [inline config/config.go:98]: NIT: could be simplified to:

```go
} else {
  return matches(name, includeREs)
}

File: config/config_test.go [hunk 3]
```diff
@@ -331,3 +332,36 @@ func TestConfigSecretsManager_FilterNames(t *testing.T) {
...
+	exclude, err := regexp.Compile(`test.*`)
+	require.NoError(t, err)
+	excludeREs := []Expression { { RE: *exclude } }
+
+	assert.False(t, ShouldInclude("test-openvpn-123", includeREs, excludeREs),
+		"Should not include when matches from the 'exclude' list")
+	assert.True(t, ShouldInclude("tf-state-bucket", includeREs, excludeREs),
+		"Should include when doesn't matches from the 'exclude' list")
+}
+func TestShouldInclude_IncludeWhenMatches(t *testing.T) {
```
Comment (brikis98) [inline config/config_test.go:356]: Nice unit tests 👍 

NIT: consider adding one for the case where there are both include and exclude values specified.

**Review by brikis98 — APPROVED** [review]
Overall, LGTM! 👍

File: config/config_test.go (hunk 3 above)
Comment (marinalimeira) [reply config/config_test.go:357]: Added another test at 43bcacbc35e

File: config/config.go (hunk 2 above)
Comment (marinalimeira) [reply config/config.go]: Ah, nice catch! Fixed b0add83

File: config/config.go (hunk 1 above)
Comment (marinalimeira) [reply config/config.go]: Fixed b0add83

**Comment by marinalimeira** [comment]
Thank you for the review, Jim! Addressed the suggestions.

**Review by brikis98 — APPROVED** [review]
LGTM!

**Review by rhoboat — APPROVED** [review]
LGTM!! Thanks for fixing this.
